"""Current October 8 applicant clauses reviewed against exact official PDFs.

These identities certify only their geographic scope and priority. Full
eligibility and supply inventories remain independently incomplete.
"""

CURRENT_REGIONAL_SOURCES = {'2026000267': {'title': '아산 그랑시티필하우스',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000267&pblancNo=2026000267&atchmnflSeqNo=1992075&atchmnflSn=3',
                'document_hash': '6d368de416fdba3c03d285a5058807e25c8f4e045c27a7cc2090f722a41dc6e7',
                'applicant_region_review': {'page': 5,
                                            'regions': [{'region_code': '44', 'region_name': '충청남도'},
                                                        {'region_code': '30', 'region_name': '대전광역시'},
                                                        {'region_code': '36', 'region_name': '세종특별자치시'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '44200',
                                                               'region_name': '충청남도 아산시',
                                                               'min_months': 0}}},
 '2026000458': {'title': '산곡역자이힐스테이트앤하늘채',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000458&pblancNo=2026000458&atchmnflSeqNo=1995089&atchmnflSn=2',
                'document_hash': '10597652e7b524abfc4b6609e00f430793f820b0732c130f94c788585285e67b',
                'applicant_region_review': {'page': 5,
                                            'regions': [{'region_code': '28', 'region_name': '인천광역시'},
                                                        {'region_code': '11', 'region_name': '서울특별시'},
                                                        {'region_code': '41', 'region_name': '경기도'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '28',
                                                               'region_name': '인천광역시',
                                                               'min_months': 0}}},
 '2026000491': {'title': '청주 가경 아이파크 7단지',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000491&pblancNo=2026000491&atchmnflSeqNo=1992167&atchmnflSn=7',
                'document_hash': '8c2e2d7123cfda85b186005f7a804294cd599825a4a75fb507b976e05d48d1c5',
                'applicant_region_review': {'page': 4,
                                            'regions': [{'region_code': '43', 'region_name': '충청북도'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '43110',
                                                               'region_name': '충청북도 청주시',
                                                               'min_months': 0}}},
 '2026000492': {'title': '청주 가경 아이파크 8단지',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000492&pblancNo=2026000492&atchmnflSeqNo=1995082&atchmnflSn=5',
                'document_hash': 'ffe93cae3b423925dea9b3aab793f89f7942eeacacfb654a55da706e336c141e',
                'applicant_region_review': {'page': 4,
                                            'regions': [{'region_code': '43', 'region_name': '충청북도'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '43110',
                                                               'region_name': '충청북도 청주시',
                                                               'min_months': 0}}},
 '2026000469': {'title': '연제갤러리자이',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000469&pblancNo=2026000469&atchmnflSeqNo=1995111&atchmnflSn=1',
                'document_hash': '937ad4e1ccc39def31b04d201bf8f2308fb9ad07c188764c3f97df471f301e69',
                'applicant_region_review': {'page': 4,
                                            'regions': [{'region_code': '26', 'region_name': '부산광역시'},
                                                        {'region_code': '31', 'region_name': '울산광역시'},
                                                        {'region_code': '48', 'region_name': '경상남도'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '26',
                                                               'region_name': '부산광역시',
                                                               'min_months': 12}}},
 '2026000466': {'title': '진도 승원팰리체 더 테라스',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000466&pblancNo=2026000466&atchmnflSeqNo=1995122&atchmnflSn=6',
                'document_hash': '96bdd74b43191dbd108987a4d1ef09686f6953fd28121a3339705959ce9e81f4',
                'applicant_region_review': {'page': 4,
                                            'regions': [{'region_code': '12', 'region_name': '전남광주통합특별시'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '12860',
                                                               'region_name': '전남광주통합특별시 진도군',
                                                               'min_months': 0},
                                            'source_regions': [{'region_code': '29',
                                                                'region_name': '기존 광주광역시'},
                                                               {'region_code': '46',
                                                                'region_name': '기존 전라남도'}]}},
 '2026000471': {'title': '한양립스 에듀포레(조합원 취소분)',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000471&pblancNo=2026000471&atchmnflSeqNo=1995080&atchmnflSn=3',
                'document_hash': '09d15961d3307e8c0fb398bd3d60fc7818e441e18f907afc0b77bd273a832600',
                'applicant_region_review': {'page': 4,
                                            'regions': [{'region_code': '12', 'region_name': '전남광주통합특별시'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '29',
                                                               'region_name': '기존 광주광역시',
                                                               'min_months': 12,
                                                               'regions': [{'region_code': '12210',
                                                                            'region_name': '전남광주통합특별시 동구'},
                                                                           {'region_code': '12240',
                                                                            'region_name': '전남광주통합특별시 서구'},
                                                                           {'region_code': '12270',
                                                                            'region_name': '전남광주통합특별시 남구'},
                                                                           {'region_code': '12300',
                                                                            'region_name': '전남광주통합특별시 북구'},
                                                                           {'region_code': '12330',
                                                                            'region_name': '전남광주통합특별시 광산구'}],
                                                               'mapping_page': 1},
                                            'source_regions': [{'region_code': '29',
                                                                'region_name': '기존 광주광역시'},
                                                               {'region_code': '46',
                                                                'region_name': '기존 전라남도'}]}},
 '2026000464': {'title': '힐스테이트 거제시그니처(1회차)',
                'announcement_date': '2026-10-08',
                'document_url': 'https://static.applyhome.co.kr/ai/aia/getAtchmnfl.do?houseManageNo=2026000464&pblancNo=2026000464&atchmnflSeqNo=1997002&atchmnflSn=1',
                'document_hash': 'ef2d66aa77a7435a4a3f0ad5830c28f484d6091f37082b6ee66f0967b7c1a627',
                'applicant_region_review': {'page': 5,
                                            'regions': [{'region_code': '48', 'region_name': '경상남도'},
                                                        {'region_code': '26', 'region_name': '부산광역시'},
                                                        {'region_code': '31', 'region_name': '울산광역시'}],
                                            'priority_applicable': True,
                                            'local_priority': {'region_code': '48310',
                                                               'region_name': '경상남도 거제시',
                                                               'min_months': 0}}}}

# All eight exact first-page 주택유형 tables explicitly say 민영.
for _source in CURRENT_REGIONAL_SOURCES.values():
    _source["housing_kind"] = "private"

# Reviewed geographic exception in each current notice's actual 군인 clause.
for _number, (_page, _area) in {
    "2026000267": (5, "local"), "2026000458": (5, "other"),
    "2026000491": (5, "local"), "2026000492": (5, "local"),
    "2026000469": (5, "other"), "2026000466": (5, "local"),
    "2026000471": (4, "other"), "2026000464": (5, "local"),
}.items():
    CURRENT_REGIONAL_SOURCES[_number]["applicant_region_review"]["military_exception"] = {
        "page": _page, "min_years": 10, "currently_serving": True,
        "residence_area": _area,
    }

CURRENT_REGIONAL_SOURCES["2026000458"]["applicant_region_review"]["additional_military_exceptions"] = [{
    "page": 5, "min_years": 25, "currently_serving": True, "residence_area": "local",
    "recommendation_required": True, "recommendation_authority": "국방부(국군복지단)",
}]

