import { useMemo } from 'react'
import { getProfileQuestionModel } from './profileQuestionModel'
import { deriveHousehold } from './household'
import { FactChangeFields } from './FactChangeFields'
import type { ApplicationHistoryEvent, ApplicationRestrictionFacts, LocalProfile, Notice, RestrictionScope } from './types'

const SCOPES: Record<RestrictionScope, string> = { applicant: '본인', applicant_spouse: '본인·배우자', household: '주택 보유를 함께 확인할 가족' }
const RESTRICTIONS = { ineligible_restriction_active: ['ineligibleRestrictionActive', '부적격 당첨으로 인한 청약 제한'], resale_restriction_active: ['resaleRestrictionActive', '공급질서 교란·전매 위반으로 인한 청약 제한'], rewinning_restriction_active: ['rewinningRestrictionActive', '재당첨 제한'] } as const
const emptyRestrictions = (): ApplicationRestrictionFacts => ({ ineligibleRestrictionActive: null, resaleRestrictionActive: null, rewinningRestrictionActive: null, asOfDate: '', historyConfirmations: [] })
function Fact({ label, value, onChange }: { label: string; value: boolean | null; onChange: (answer: boolean | null) => void }) { return <fieldset className="radio-field"><legend>{label}</legend><div>{([[true, '예'], [false, '아니요'], [null, '모름']] as const).map(([answer, text]) => <button type="button" key={text} aria-pressed={value === answer} className={value === answer ? 'chosen' : ''} onClick={() => onChange(answer)}>{text}</button>)}</div></fieldset> }
const EVENT_KINDS = [['winning', '당첨'], ['reserve_winning', '예비당첨'], ['contract', '주택 공급계약'], ['additional_resident_contract', '예비입주자 추가 공급계약']] as const

export function ApplicationFactsFields({ profile, onChange, today, notices, section }: { profile: LocalProfile; onChange: (value: LocalProfile) => void; today: string; notices: Notice[]; section: 'residence' | 'restrictions' }) {
  const relevant = useMemo(() => { const model = getProfileQuestionModel(notices, today); return section === 'residence' ? model.residenceRules : model.restrictionRules }, [notices, today, section])
  if (!relevant.length) return null
  if (section === 'residence') {
    const overseas = relevant.filter(({ rule }) => rule.kind === 'overseas_residence')
    return <section className="question-group application-facts"><h4>국적·해외 거주 사실</h4>
      {relevant.some(({ rule }) => rule.kind === 'citizenship') && <label data-profile-field="citizenship">현재 국적<select value={profile.citizenship} onChange={(event) => onChange({ ...profile, citizenship: event.target.value as LocalProfile['citizenship'] })}><option value="unknown">국적 선택</option><option value="korean">대한민국</option><option value="foreign">외국 국적</option></select></label>}
      <FactChangeFields profile={profile} onChange={onChange} today={today} group="citizenship" label="국적" needed={relevant.some(({ rule, date }) => rule.kind === 'citizenship' && !!date && date < today)} />
      {!!overseas.length && <><label data-profile-field="overseasContinuousDays">현재 연속 해외 체류 일수 (일)<input type="number" min="0" step="1" inputMode="numeric" value={profile.overseasContinuousDays} onChange={(event) => onChange({ ...profile, overseasContinuousDays: event.target.value })} /></label><p className="field-help">계속 국내에 있었다면 0일입니다. 출입국사실증명으로 확인하세요. 공고 기준의 귀국 후 재출국 합산 규칙은 별도 적용합니다.</p>{Number(profile.overseasContinuousDays) > 90 && <div data-profile-field="overseasOnlyApplicantForLivelihood"><Fact label="본인만 생업을 위해 해외에 있고, 배우자·확인 대상 가족은 국내에 거주하나요?" value={profile.overseasOnlyApplicantForLivelihood} onChange={(answer) => onChange({ ...profile, overseasOnlyApplicantForLivelihood: answer })} /></div>}<FactChangeFields profile={profile} onChange={onChange} today={today} group="overseas" label="해외 체류 상태" needed={overseas.some(({ date }) => !!date && date < today)} /></>}
    </section>
  }
  const scoped = (['applicant', 'applicant_spouse', 'household'] as const).map((scope) => ({ scope, rules: relevant.filter(({ rule }) => rule.scope === scope && String(rule.restriction) in RESTRICTIONS) })).filter((item) => item.rules.length)
  const projectRules = relevant.filter(({ rule }) => ['prior_project_winner', 'prior_project_contract'].includes(String(rule.restriction)))
  const projects = [...new Map(projectRules.map(({ rule, notice }) => [String(rule.project_id || ''), { id: String(rule.project_id || ''), title: notice.title }])).values()].filter((project) => project.id)
  const people = deriveHousehold(profile).members.filter((member) => member.included === true)
  const currentPeople = people.map((person) => person.id)
  const missingPeople = people.filter((person) => !profile.applicationHistoryPeople.includes(person.id))
  const patchEvent = (id: string, part: Partial<ApplicationHistoryEvent>) => onChange({ ...profile, applicationHistoryComplete: null, applicationHistoryEvents: profile.applicationHistoryEvents.map((event) => event.id === id ? { ...event, ...part } : event) })
  return <section className="question-group application-facts"><h4>공통 당첨·계약 이력과 현재 청약 제한</h4><p className="field-help">공고마다 다시 묻지 않습니다. 입력한 사람·최초 사업·사건 날짜를 각 공고의 실제 제한과 비교합니다.</p><a href="https://www.applyhome.co.kr/" target="_blank" rel="noopener noreferrer">청약홈에서 이력·제한사항 확인</a>
    {!!projectRules.length || relevant.some(({ rule }) => ['previous_winning', 'special_winning'].includes(rule.kind)) ? <section className="ownership-item" data-profile-field="applicationHistoryPresence"><h5>당첨·계약 이력 한 번 입력</h5><p className="field-help">확인 대상: {people.map((person) => person.label).join(' · ')}. 청약·예비당첨·계약 이력이 없는 사람도 이 답변에 포함됩니다.</p><Fact label="위 사람 중 당첨·예비당첨 또는 주택 공급계약 이력이 있는 사람이 있나요?" value={profile.applicationHistoryPresence} onChange={(answer) => onChange({ ...profile, applicationHistoryPresence: answer, applicationHistoryComplete: answer === false ? true : null, applicationHistoryPeople: answer === false ? currentPeople : profile.applicationHistoryPeople })} />
      {profile.applicationHistoryPresence !== null && !!missingPeople.length && profile.applicationHistoryComplete === true && <div className="field-help"><p>새로 추가한 확인 대상: {missingPeople.map((person) => person.label).join(' · ')}</p><button type="button" className="text-button" onClick={() => onChange({ ...profile, applicationHistoryPresence: null, applicationHistoryComplete: null })}>추가한 사람의 이력 포함하기</button></div>}
      {profile.applicationHistoryPresence === true && <div data-profile-field="applicationHistoryEvents">{profile.applicationHistoryEvents.map((event, index) => <section className="ownership-item" key={event.id}><h5>이력 {index + 1}</h5><label>해당 사람<select value={event.personId} onChange={(input) => patchEvent(event.id, { personId: input.target.value })}><option value="">사람 선택</option>{people.map((person) => <option key={person.id} value={person.id}>{person.label}</option>)}{event.personId && !currentPeople.includes(event.personId) && <option value={event.personId}>기존 이력의 가족</option>}</select></label><label>최초 사업번호<input type="text" list="application-history-projects" value={event.projectId} onChange={(input) => patchEvent(event.id, { projectId: input.target.value.trim() })} placeholder="청약홈 사업번호 또는 LH 사업번호" /></label><label>사건 종류<select value={event.eventKind} onChange={(input) => patchEvent(event.id, { eventKind: input.target.value as ApplicationHistoryEvent['eventKind'] })}>{EVENT_KINDS.map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select></label>{['winning', 'reserve_winning'].includes(event.eventKind) && relevant.some(({ rule }) => rule.kind === 'special_winning') && <Fact label="특별공급 당첨·예비당첨인가요?" value={event.specialSupply ?? null} onChange={(answer) => patchEvent(event.id, { specialSupply: answer })} />}<label>실제 사건 날짜<input type="date" max={today} value={event.eventDate} onChange={(input) => patchEvent(event.id, { eventDate: input.target.value })} /></label><button type="button" className="text-button" onClick={() => onChange({ ...profile, applicationHistoryComplete: null, applicationHistoryEvents: profile.applicationHistoryEvents.filter((other) => other.id !== event.id) })}>이력 삭제</button></section>)}<datalist id="application-history-projects">{projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</datalist><button type="button" className="add-fact" onClick={() => onChange({ ...profile, applicationHistoryComplete: null, applicationHistoryEvents: [...profile.applicationHistoryEvents, { id: crypto.randomUUID(), personId: 'applicant', projectId: '', eventKind: 'winning', eventDate: '' }] })}>이력 추가</button><Fact label="위 확인 대상의 당첨·계약 이력을 모두 입력했나요?" value={profile.applicationHistoryComplete} onChange={(answer) => onChange({ ...profile, applicationHistoryComplete: answer, applicationHistoryPeople: answer === true ? currentPeople : profile.applicationHistoryPeople })} /></div>}
    </section> : null}
    {scoped.map(({ scope, rules }) => {
      const entry = profile.applicationRestrictionFacts[scope] || emptyRestrictions()
      const patch = (part: Partial<ApplicationRestrictionFacts>) => onChange({ ...profile, applicationRestrictionFacts: { ...profile.applicationRestrictionFacts, [scope]: { ...entry, ...part, asOfDate: today, historyConfirmations: [] } } })
      const kinds = [...new Set(rules.map(({ rule }) => rule.restriction as keyof typeof RESTRICTIONS))]
      return <section key={scope} className="ownership-item" data-profile-field="applicationRestrictionFacts"><h5>{SCOPES[scope]}의 현재 청약 제한</h5>{kinds.map((kind) => { const [field, label] = RESTRICTIONS[kind]; return <Fact key={kind} label={`현재 청약홈에 ${label}가 표시되나요?`} value={entry[field]} onChange={(answer) => patch({ [field]: answer })} /> })}</section>
    })}
    <FactChangeFields profile={profile} onChange={onChange} today={today} group="restrictions" label="청약 제한 상태" needed={scoped.some(({ rules }) => rules.some(({ date }) => !!date && date < today))} />
  </section>
}
